# Generated by Django 5.1 on 2024-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('es_moderada', models.BooleanField(default=False)),
                ('es_pagada', models.BooleanField(default=False)),
                ('para_suscriptores', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_contenido', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
