# Generated by Django 5.1 on 2024-09-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
