# Generated by Django 5.1 on 2024-10-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoria_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
