# Generated by Django 5.1 on 2024-09-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id_conte', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_conte', models.CharField(max_length=255)),
                ('tipo_conte', models.CharField(max_length=50)),
                ('texto_conte', models.TextField()),
                ('estado_conte', models.CharField(max_length=50)),
                ('fecha_conte', models.DateField()),
                ('cant_visualiz_conte', models.IntegerField(default=0)),
                ('cant_coment_conte', models.IntegerField(default=0)),
            ],
        ),
    ]
