# Generated by Django 5.1 on 2024-09-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_agregar_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazos', to='contenido.contenido')),
            ],
        ),
    ]
