# Generated by Django 5.1 on 2024-09-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_contenido_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contenido',
            name='unlikes',
            field=models.IntegerField(default=0),
        ),
    ]
