# Generated by Django 5.1 on 2024-10-04 02:49

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0012_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.PositiveIntegerField()),
                ('titulo_conte', models.CharField(max_length=255)),
                ('tipo_conte', models.CharField(max_length=50)),
                ('texto_conte', ckeditor.fields.RichTextField()),
                ('fecha_version', models.DateTimeField(default=django.utils.timezone.now)),
                ('contenido_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='contenido.contenido')),
            ],
        ),
    ]
