# Generated by Django 5.1 on 2024-10-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0013_contenido_average_rating_contenido_total_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='total_stars',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
