# Generated by Django 5.1 on 2024-10-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0014_remove_contenido_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votocontenido',
            name='estrellas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votocontenido',
            name='tipo_voto',
            field=models.CharField(blank=True, choices=[('LIKE', 'Like'), ('UNLIKE', 'Unlike')], max_length=6, null=True),
        ),
    ]
