# Generated by Django 5.1 on 2024-10-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0014_cambioborrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='autopublicar_conte',
            field=models.BooleanField(default=False),
        ),
    ]
