# Generated by Django 5.1 on 2024-10-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0015_contenido_autopublicar_conte'),
        ('contenido', '0015_reportecontenido'),
    ]

    operations = [
    ]
