# Generated by Django 5.1 on 2024-10-05 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0016_merge_20241005_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='version_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenido_version_actual', to='contenido.versioncontenido'),
        ),
    ]
