# Generated by Django 5.1 on 2024-10-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0016_merge_20241005_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='imagen_conte',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
