# Generated by Django 5.1 on 2024-10-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0018_historialcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='fecha_vigencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='vigencia_conte',
            field=models.BooleanField(default=True),
        ),
    ]
