# Generated by Django 5.1 on 2024-10-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0021_cambioestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioestado',
            name='razon_revision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
