# Generated by Django 5.1 on 2024-10-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0017_alter_contenido_imagen_conte'),
        ('contenido', '0022_cambioestado_razon_revision'),
    ]

    operations = [
    ]
