# Generated by Django 5.1 on 2024-10-25 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0023_merge_20241006_2321'),
        ('contenido', '0023_rating'),
    ]

    operations = [
    ]
