# Generated by Django 5.1 on 2024-11-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0023_merge_20241006_2321'),
        ('contenido', '0025_contenido_es_destacado'),
    ]

    operations = [
    ]
