# Generated by Django 5.1 on 2024-11-07 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0024_merge_0023_merge_20241006_2321_0023_rating'),
        ('contenido', '0025_contenido_es_destacado'),
    ]

    operations = [
    ]
