# Generated by Django 5.1 on 2024-11-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0025_contenido_es_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompra',
            name='metodo_pago',
            field=models.CharField(default='stripe', max_length=50),
        ),
    ]
