# Generated by Django 5.1 on 2024-11-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0026_historialcompra_metodo_pago'),
        ('contenido', '0026_merge_20241108_1325'),
    ]

    operations = [
    ]
