# Generated by Django 5.1 on 2024-11-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0027_contenido_comparticiones_copiar_enlace_and_more'),
        ('contenido', '0027_merge_20241108_1346'),
    ]

    operations = [
    ]
