# Generated by Django 5.1 on 2024-10-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_sales', 'Can view sales'), ('filter_sales', 'Can filter sales')],
            },
        ),
    ]
