version: "3"

services:
  db:
    image: postgres:latest # 16
    environment:
      POSTGRES_DB: leticia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/leticia
      - DJANGO_ENV=produccion
    expose:
      - "8000"
    volumes:
      - django_static:/app/staticfiles
      - django_media:/app/media

  pictshare:
    image: ghcr.io/hascheksolutions/pictshare
    container_name: pictshare
    ports:
      - "9080:80"
    volumes:
      - ./data:/var/www/html/upload/imagenes_contenido
    environment:
      - ALLOW_ALL=1
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80" # For HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - django_static:/app/staticfiles
      - django_media:/app/media
    depends_on:
      - web

volumes:
  django_media:
  django_static:
